services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: senha123
    ports: ["3306:3306"]

  api:
    image: projcardapio:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["8080:8080"]